#!/usr/bin/env bash
#
# This hook is executed by git after receiving data that was pushed to this
# repository. $GIT_DIR will point to ?/myblog/git/ where it will find ./HEAD
# and ./refs/heads/master. As per the directory structure of lenie the source
# files (*.md and rc.lua) are to be checked out to ?/myblog/src/, which is at
# ../src/ relative to $GIT_DIR.

# 1. Check out all the source files (markdown files etc) from this bare repo
# into the src directory
echo "PWD is $PWD and GIT_DIR is $GIT_DIR"
SRCDIR="${GIT_DIR}/../src"
echo "SRCDIR is at $SRCDIR"
GIT_WORK_TREE="$SRCDIR" git checkout -f

# 2. Run lenie on the src directory and let her write the generated HTML and CSS
# files to the directory the webserver is reading from.

/usr/local/bin/lenie generate "$SRCDIR" "/srv/www"
